// AUTH Constants
export const AUTH: string = 'AUTH'
export const CLEAR_MESSAGE: string = 'CLEAR_MESSAGE'
export const CLEAR_SPECIAL_MESSAGE: string = 'CLEAR_SPECIAL_MESSAGE'
export const INVALID_CREDENTIALS: string = 'INVALID_CREDENTIALS'
export const LOGOUT: string = 'LOGOUT'
export const UPDATEPASSWORDMESSAGE: string = 'UPDATEPASSWORDMESSAGE'
export const VALIDATE_PASSWORD: string = 'VALIDATE_PASSWORD'

// Record Constants

export const CREATERECORD = 'CREATERECORD'
export const DELETERECORD = 'DELETERECORD'
export const GETALLRECORDSOFUSER = 'GETALLRECORDSOFUSER'
export const GETRECORD = 'GETRECORD'
export const SERVERERROR = 'SERVERERROR'
export const UPDATERECORD = 'UPDATERECORD'
